# Generated by Django 6.0 on 2026-01-05 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only letters and numbers are allowed.')])),
                ('vehicle_type', models.CharField(choices=[('Two', 'Two Wheelar'), ('Three', 'Three Wheelar'), ('Four', 'Four Wheelar')], max_length=10)),
                ('vehicle_model', models.CharField(max_length=10)),
                ('vehicle_description', models.TextField(max_length=100)),
            ],
        ),
    ]
